### ISSUE TITLE
请问请求参数的编码方式什么？

### ISSUE THREAD

**Issue by AlexJakin** [di0xide-U/YSTupload#1]
AFMALANMJCEOENIBDJMKFHBANGEPKHNOFJBMIFJPFNKFOKHJNMLCOIDDJGNEIPOLOKGAFAFJHDEJPHEPLFJHDGPBNELNFIICGFNGEOEFBKCDDCGJEPIKFHJFAOOHJEPNNCLFHDAFDNCGBAEELJFFHABJPDPIEEMIBOECDMDLEPBJGBGCGLEMBDFAGOGM 请问这串请求参数的是什么编码

**Comment by di0xide-U** [comment]
public class test {           
    public static void main(String[] args) throws Exception {          
        String enc = CDGUtil.encode("需要加密的内容");          
        System.out.println(enc);          
    }          
}

**Comment by AlexJakin** [comment]
请问大佬CDGUtil类哪个 能给一下吗
